name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 1.0.31
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.1
  just_audio: ^0.9.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


